### ISSUE TITLE
Error when I overwithdraw

### ISSUE THREAD

**Issue by St3rling0x** [lukechilds/hyperdex#255] opened 2018-05-21 17:08 UTC
Uncaught error when I withdraw over the limit

Unhandled Promise Rejection
Error: Couldn't create withdrawal transaction:
{ txid: '0000000000000000000000000000000000000000000000000000000000000000',
  txfee: 1000,
  complete: false }
    at errorWithObject (app://-/bundle.js:89658:46)
    at app://-/bundle.js:89915:11
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:89647:191)
    at app://-/bundle.js:89647:361
    at <anonymous>

---

HyperDEX Nightly 0.0.0-990420d-18.5.21.1359
Electron 2.0.1
darwin 17.5.0
Locale: en-US

**Comment by lukechilds** [comment] 2018-06-15 12:05
Closing this as it's a duplicate of https://github.com/lukechilds/hyperdex/issues/201

**Closed by lukechilds** 2018-06-15 12:05 UTC
