### ISSUE TITLE
Error on second withdrawal

### ISSUE THREAD

**Issue by Erlix322** [lukechilds/hyperdex#254] opened 2018-05-21 16:42 UTC
Hi,

i withdrawed some Beer to my own address to get utxos.
First i withdrawed 1 Beer and after that I tried to withdraw another one and the second one failed with this error

Unhandled Promise Rejection
Error: Couldn't create withdrawal transaction:
{ txid: '0000000000000000000000000000000000000000000000000000000000000000',
  txfee: 1000,
  complete: false }
    at errorWithObject (app://-/bundle.js:90100:46)
    at app://-/bundle.js:90357:11
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:90089:191)
    at app://-/bundle.js:90089:361
    at <anonymous>

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 10.0.16299
Locale: de

**Comment by lukechilds** [comment] 2018-06-15 12:05
Closing this as it's a duplicate of https://github.com/lukechilds/hyperdex/issues/201

**Closed by lukechilds** 2018-06-15 12:05 UTC
