### ISSUE TITLE
Error when withdrawing to the deposit address multiple times

### ISSUE THREAD

**Issue by gcharang** [lukechilds/hyperdex#309] opened 2018-05-24 12:06 UTC
I was sending little amounts of $BEER to myself(Deposit address in Hyperdex) for the purpose of UTXO splitting. After 3 - 4 succcesive withdrawals (0.1, 1, 10) this error appeared when I tried to withdraw again

Unhandled Promise Rejection
Error: Couldn't create withdrawal transaction:
{ txid: '0000000000000000000000000000000000000000000000000000000000000000',
  txfee: 1000,
  complete: false }
    at errorWithObject (app://-/bundle.js:89745:46)
    at app://-/bundle.js:90002:11
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:89734:191)
    at app://-/bundle.js:89734:361
    at <anonymous>
---

HyperDEX Nightly 0.0.0-e08a542-18.5.23.1401
Electron 2.0.2
linux 4.13.0-43-generic
Locale: en-GB

**Comment by gcharang** [comment] 2018-05-26 13:56
Also, when withdrawing to the same address as the deposit address (In HyperDEX, for BEER and PIZZA tokens) for the puspose of UTXO splitting, no matter the withdrawal amount no extra utxo is formed and a transaction that appears to be for zero transfer seems to be submitted which causes transaction fee to be spent.
Ex: UTXOs before trying to withdraw various amounts(BEER) to the same address
[  
   {  
      "tx_hash":"c307d0a76b84136d497847e84e7c4adff0c1ae0bf5fa93fd7fb8ffc24f5df922",
      "tx_pos":0,
      "height":40093,
      "value":448899993550
   },
   {  
      "tx_hash":"5ca97c95eb10547ab59709db6fc3c80327e927f60bfe35fb96bdf08883123b06",
      "tx_pos":0,
      "height":40094,
      "value":449999997550
   },
   {  
      "tx_hash":"69264ecbbbf8fbd337a94917b29f5f4d921a95771e7a7d18b279ef9068ba4196",
      "tx_pos":0,
      "height":40103,
      "value":43899988900
   }
]

UTXOs after attempting to withdraw 4 different amounts to the deposit address(i.e, same address):
[
  {
    "tx_hash": "c307d0a76b84136d497847e84e7c4adff0c1ae0bf5fa93fd7fb8ffc24f5df922",
    "tx_pos": 0,
    "height": 40093,
    "value": 448899993550
  },
  {
    "tx_hash": "5ca97c95eb10547ab59709db6fc3c80327e927f60bfe35fb96bdf08883123b06",
    "tx_pos": 0,
    "height": 40094,
    "value": 449999997550
  },
  {
    "tx_hash": "8017b676138926593f8e423acd212fbec31e1d430ade26fce175c76faa17da26",
    "tx_pos": 0,
    "height": 40320,
    "value": 43899984900
  }
]
here the last utxo has 43899984900. before withdrawals it was 43899988900 so 4 tx fee are cut but no extra utxo are formed. The top two UTXO haven't been touched. But the bottom UTXO got destroyed and created 4 times, each time losing 0.00001000 value.

**Comment by lukechilds** [comment] 2018-06-15 12:06
Closing this as it's a duplicate of https://github.com/lukechilds/hyperdex/issues/201

**Closed by lukechilds** 2018-06-15 12:06 UTC
