### ISSUE TITLE
Translate Hyperdex into a different language

### ISSUE THREAD

**Issue by ip-config** [lukechilds/hyperdex#315] opened 2018-05-25 12:57 UTC
Hey,
How i can help to translate Hyperdex to other language ?

**Comment by sindresorhus** [comment] 2018-05-25 14:30
Duplicate of #178

**Comment by sindresorhus** [comment] 2018-05-25 14:31
@ip-config Subscribe to #178. We're not quite ready to translate the app yet. The English text is not all done and we don't want to waste translators time, but it's a priority to get translations done before the official release.

**Closed by sindresorhus** 2018-05-25 14:30 UTC
