### ISSUE TITLE
Swap pending

### ISSUE THREAD

**Issue by lilszi** [lukechilds/hyperdex#287] opened 2018-05-22 12:43 UTC
So if there is no match for a swap after a minute, it goes "unmatched". So if i let it expire, the status changes to "unmatched". But if I create another swap right after the 60 seconds passed, but before the status changes, it is  stuck in "pending" forever, never changes to "unmatched" and can not cancel. 

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 6.1.7601
Locale: en-US

**Comment by lukechilds** [comment] 2018-05-28 23:47
This is a `marketmaker` bug and a duplicate of issue https://github.com/lukechilds/hyperdex/issues/279

**Closed by lukechilds** 2018-05-28 23:47 UTC
Labels: marketmaker related
